name: Release

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    name: Build and push Docker image
    needs: test
    with:
      tag: rc
    secrets:
      dockerUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerPassword: ${{ secrets.DOCKERHUB_TOKEN }}