name: Release latest

on:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    name: Build and push Docker image
    needs: test
    with:
      tag: latest
    secrets:
      dockerUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerPassword: ${{ secrets.DOCKERHUB_TOKEN }}